// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgA0xnDPAqxFQGfQxn7EF9rZeE26tExPg',
    appId: '1:388558956260:web:19b183e1437f20873f2ef1',
    messagingSenderId: '388558956260',
    projectId: 'drain-monitor-live',
    authDomain: 'drain-monitor-live.firebaseapp.com',
    databaseURL: 'https://drain-monitor-live-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'drain-monitor-live.firebasestorage.app',
    measurementId: 'G-JGH89PGQTR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBISSP_bC_pKOKDPKkbMK6Ngx8vKsT6NLs',
    appId: '1:388558956260:android:a9192726e0c14b1c3f2ef1',
    messagingSenderId: '388558956260',
    projectId: 'drain-monitor-live',
    databaseURL: 'https://drain-monitor-live-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'drain-monitor-live.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBaPQaw3fB_sHMdmGaP44F70R6Hm5GmaiA',
    appId: '1:388558956260:ios:3340bf49fa04d8083f2ef1',
    messagingSenderId: '388558956260',
    projectId: 'drain-monitor-live',
    databaseURL: 'https://drain-monitor-live-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'drain-monitor-live.firebasestorage.app',
    iosBundleId: 'com.example.gpsTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBaPQaw3fB_sHMdmGaP44F70R6Hm5GmaiA',
    appId: '1:388558956260:ios:3340bf49fa04d8083f2ef1',
    messagingSenderId: '388558956260',
    projectId: 'drain-monitor-live',
    databaseURL: 'https://drain-monitor-live-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'drain-monitor-live.firebasestorage.app',
    iosBundleId: 'com.example.gpsTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDgA0xnDPAqxFQGfQxn7EF9rZeE26tExPg',
    appId: '1:388558956260:web:c5bee7e666c988113f2ef1',
    messagingSenderId: '388558956260',
    projectId: 'drain-monitor-live',
    authDomain: 'drain-monitor-live.firebaseapp.com',
    databaseURL: 'https://drain-monitor-live-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'drain-monitor-live.firebasestorage.app',
    measurementId: 'G-04WEBP4R0C',
  );
}
